dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
# Regarding goerli network settings...
# "0x9326BFA02ADD2366b30bacB125260Af641031331" is the address for the
#   ETH / USD price feed on the KOVAN network. My contract is being
#   created on the Goerli network. Chainlink does not have Goerli
#   price feeds so I'm using Kovan's address.
networks:
  # default is automatically 'development'; don't need to set it here
  default: development
  kovan:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True
  goerli:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False  
wallets:
  from_key: ${PRIVATE_KEY}
    